<a href="https://colab.research.google.com/github/SenaKymk/MachineLearning201/blob/main/CokluDogrusalRegresyon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import statsmodels.api as sm

In [8]:
df= pd.read_csv("/Advertising.csv")
df= df.iloc[:,1:len(df)]
df.head()


TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [9]:
X=df.drop("sales",axis =1)
y=df[["sales"]]

In [4]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [10]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [11]:
#statsmodel ile
lm =sm.OLS(y,X)

In [12]:
model=lm.fit()


In [13]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Mon, 23 Dec 2024   Prob (F-statistic):                   2.43e-171
Time:                        18:41:27   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [15]:
#model kurma işlemi
from sklearn.linear_model import LinearRegression
lm= LinearRegression()

In [16]:
model = lm.fit(X,y)


In [17]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

In [18]:
model.intercept_

array([2.93888937])

In [26]:
import pandas as pd
yeni_veri =[[30],[10],[40]]
yeni_veri = pd.DataFrame(yeni_veri).T
yeni_veri

0   1   2
0  30  10  40

In [27]:
#tahmin
model.predict(yeni_veri)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6.15562918]])

In [28]:
from sklearn.metrics import mean_squared_error
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [29]:
model.predict(X)[0:10]

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [32]:
mse= mean_squared_error(y,model.predict(X))
mse

2.784126314510936

In [34]:
import numpy as np
rmse=np.sqrt(mse)
rmse

1.6685701407225697

**ÇOKLU DOĞRUSAL REGRESYON MODEL TUNİNG**

In [35]:
from sklearn.model_selection import train_test_split

In [49]:
X_train ,X_test ,y_train, y_test =train_test_split(X,y,test_size=0.20, random_state=11)

In [50]:
X_train.head()

TV  radio  newspaper
163  163.5   36.8        7.4
137  273.7   28.9       59.7
30   292.9   28.3       43.2
103  187.9   17.2       17.9
98   289.7   42.3       51.2

In [51]:
lm= LinearRegression()
model= lm.fit(X_train,y_train)

In [52]:
#eğitim hatası
np.sqrt(mean_squared_error(y_train,model.predict(X_train)))


1.504516150180384

In [53]:
#test hatası
np.sqrt(mean_squared_error(y_test,model.predict(X_test)))

2.275495465931183

In [54]:
# k katlı cross validation bizim için çok önemli çünkü eğitim için seçeceğimiz yüzde 80 lik kısmı nerden alacağımızı bu yöntem ile buluruz
from sklearn.model_selection import cross_val_score


In [57]:
mse=np.mean(-cross_val_score(model, X_train,y_train,cv=10, scoring="neg_mean_squared_error"))
mse

2.425461714560921

In [59]:
rmse= np.sqrt(np.mean(-cross_val_score(model, X_train,y_train,cv=10, scoring="neg_mean_squared_error")))
rmse

1.557389390795032