<a href="https://colab.research.google.com/github/SenaKymk/MachineLearning201/blob/main/labML2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
import time
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [50]:
df = pd.read_csv("/content/diabetes.csv")
#verinin ilk 5 satırını gösterir
veri.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [51]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [52]:
type(df)

pandas.core.frame.DataFrame

In [53]:
df.shape

(768, 9)

In [54]:
x=df.drop(["Outcome"],axis=1)
y=df["Outcome"]

In [55]:
x.shape


(768, 8)

In [56]:
y.shape

(768,)

In [57]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42,stratify=y)
#sınıf dağılımının aynı olamsı için



In [58]:
X_train_bias = np.c_[np.ones((X_train.shape[0], 1)), X_train]
X_test_bias = np.c_[np.ones((X_test.shape[0], 1)), X_test]

In [59]:
type(y_train)

pandas.core.series.Series

In [60]:
y_train=y_train.to_numpy().reshape(-1,1)

In [61]:
y_train.shape

(614, 1)

In [62]:
weights_initial = np.zeros((X_train_bias.shape[1],))*0.01

In [63]:
weights_initial.shape

(9,)

In [64]:
weights_initial= weights_initial.reshape(-1,1)

In [65]:
weights_initial.shape

(9, 1)

In [68]:
def sigmoid(Z):
  return 1/(1+np.exp(-Z))

In [69]:
def compute_cost(X, y, W):
    Z=np.dot(X,W)
    y_pred=sigmoid(Z)
    cost=y*np.log(y_pred)+(1-y)*np.log(1-y_pred)
    return -np.mean(cost)

In [71]:
def gradient_descent(X, y, W, learning_rate=0.001, n_steps= 10000, print_cost=True):
    m = X.shape[0]
    costs = []
    for i in range(n_steps):
      Z=np.dot(X,W)
      y_pred=sigmoid(Z)
      gradient=np.dot(X.T,(y_pred-y))/m
      W=W-learning_rate*gradient

      if print_cost and i % 1000 == 0:
            print ("Cost after iteration %i: %f" %(i, compute_cost(X, y, W)) )



    return W

In [72]:
weights_final= gradient_descent(X_train_bias,y_train,weights_initial,learning_rate=0.0001, n_steps= 10000, print_cost=True)


Cost after iteration 0: 0.675580
Cost after iteration 1000: 0.617426
Cost after iteration 2000: 0.615484
Cost after iteration 3000: 0.614050
Cost after iteration 4000: 0.612973
Cost after iteration 5000: 0.612153
Cost after iteration 6000: 0.611519
Cost after iteration 7000: 0.611019
Cost after iteration 8000: 0.610618
Cost after iteration 9000: 0.610286


In [73]:
weights_final

array([[-0.03813113],
       [ 0.08395   ],
       [ 0.01313892],
       [-0.03098216],
       [-0.0004987 ],
       [ 0.00134199],
       [-0.00066392],
       [ 0.00315438],
       [-0.00869645]])

In [74]:
y_pred_probs= sigmoid(np.dot(X_test_bias,weights_final))

In [75]:
y_pred_probs.shape

(154, 1)

In [76]:
y_pred_probs[:5]

array([[0.57214947],
       [0.12277507],
       [0.35082531],
       [0.43854616],
       [0.71321465]])

In [77]:
y_preds= (y_pred_probs > 0.5).astype(int)

In [78]:
y_preds[:5]

array([[1],
       [0],
       [0],
       [0],
       [1]])

In [81]:
print(y_preds.shape)
print(y_test.shape)


(154, 1)
(154,)


In [82]:
y_preds = y_preds.ravel()
# veya
y_preds = np.squeeze(y_preds)


In [83]:
accuracy = np.mean(y_preds == y_test)
print("Accuracy:", accuracy)


Accuracy: 0.6818181818181818


In [84]:
weights_initial= weights_initial.reshape(-1,1)
y_pred_probs= sigmoid(np.dot(X_test_bias,weights_initial))
y_preds= (y_pred_probs > 0.5).astype(int)
y_preds = y_preds.ravel()
accuracy = np.mean(y_preds == y_test)
print("Accuracy:", accuracy)

Accuracy: 0.6493506493506493


In [85]:
weights_initial = np.zeros((X_train_bias.shape[1],))*0.01
weights_initial= weights_initial.reshape(-1,1)
y_pred_probs= sigmoid(np.dot(X_test_bias,weights_initial))
y_preds= (y_pred_probs > 0.5).astype(int)
y_preds = y_preds.ravel()
accuracy = np.mean(y_preds == y_test)
print("Accuracy:", accuracy)

Accuracy: 0.6493506493506493
